// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSiRZAFt7Teup8byl7xyK0YM_GwSrH7aM',
    appId: '1:549390527515:web:80ecf22f517dad6e3f9cbe',
    messagingSenderId: '549390527515',
    projectId: 'firebase-storage-crud-simple',
    authDomain: 'fir-storage-crud-simple.firebaseapp.com',
    storageBucket: 'firebase-storage-crud-simple.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi4O-BABC91c2T8LgCgOq8RwZ5fKdyY60',
    appId: '1:549390527515:android:7b6257eaa16630f93f9cbe',
    messagingSenderId: '549390527515',
    projectId: 'firebase-storage-crud-simple',
    storageBucket: 'firebase-storage-crud-simple.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALbvuUeMBmPnKICSFq86npBqoD4vU-s74',
    appId: '1:549390527515:ios:0ac9db20fcc8fd413f9cbe',
    messagingSenderId: '549390527515',
    projectId: 'firebase-storage-crud-simple',
    storageBucket: 'firebase-storage-crud-simple.appspot.com',
    iosClientId: '549390527515-59k8giphf7n4q9lp0l7t56h5kgcit8hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStorageCrudSimple2022',
  );
}
